### ISSUE TITLE
Lack of expected uniform coverage when using the `--refBias no` argument

### ISSUE THREAD

**Issue by tinyheero** [schmeing/ReSeq#10]
Hi,

I've been using the `--refBias no` argument to try to generate uniform coverage, but the results have a much larger variance than I would have expected.

I've produced a minimal example to demonstrate this (please see this [folder](https://drive.google.com/drive/folders/1oPAitRV6REmTewB00ERNnuuBfoll1P4D?usp=sharing) for the input and output files). This minimal example consists of:

1. A ReSeq profile that has been trained using the NA12878 sample on the hg19 genome FASTA (`input/reseq_profile/NA12878.sorted.bam.reseq`).
1. A subsetted FASTA file that is the subset of the hg19 genome FASTA (`input/reference/ucsc.hg19-GATKBundle.subset.fa`). Specifically the reference sequences in this file correspond to specific exons/regions of interest.

Since the subsetted FASTA file does not match the FASTA reference used to train the ReSeq profile (i.e. file 1), the `--refBias no` argument is used (as highlighted in this issue https://github.com/schmeing/ReSeq/issues/9#issuecomment-767392750). The intent is to use the profile for sequence error simulation, but have relatively uniform coverage using `--refBias no`. The following is then run:

```bash
[[ -d logs ]] || mkdir logs
[[ -d sim_fastqs ]] || mkdir sim_fastqs
[[ -d sim_bam ]] || mkdir sim_bam
[[ -d picard ]] || mkdir picard
[[ -d interval_list ]] || mkdir interval_list

reseq illuminaPE \
        -j 4 \
        --statsIn input/reseq_profile/NA12878.sorted.bam.reseq \
        --ipfIterations 0 \
        -r input/reference/ucsc.hg19-GATKBundle.subset.fa \
        -1 sim_fastqs/reseq-R1_no_refbias.fq.gz \
        -2 sim_fastqs/reseq-R2_no_refbias.fq.gz \
        --refBias no \
        --coverage 200 \
        --seed 12345 \
    > logs/reseq_sim_no_refbias.stdout \
    2> logs/reseq_sim_no_refbias.stderr

bwa mem \
        -t 4 \
        -R "@RG\tID:reseq\tSM:RESEQ\tPL:ILLUMINA" \
        -M "input/reference/ucsc.hg19-GATKBundle.subset.fa" \
        "sim_fastqs/reseq-R1_no_refbias.fq.gz" \
        "sim_fastqs/reseq-R2_no_refbias.fq.gz" \
    2> logs/reseq_no_refbias_bwa_mem.stderr \
    | picard SortSam \
        INPUT=/dev/stdin \
        OUTPUT=sim_bam/reseq_no_refbias.sorted.bam \
        SORT_ORDER=coordinate \
    2> logs/reseq_no_refbias_sort_sam.stderr

samtools index sim_bam/reseq_no_refbias.sorted.bam

picard BedToIntervalList \
        INPUT=input/reference/ucsc.hg19-GATKBundle.subset.fa.bed \
        OUTPUT=interval_list/hg19_subset.interval_list \
        SD=sim_bam/reseq_no_refbias.sorted.bam

picard CollectHsMetrics \
        INPUT=sim_bam/reseq_no_refbias.sorted.bam \
        OUTPUT=picard/reseq_no_refbias.hs_metrics.txt \
        R=input/reference/ucsc.hg19-GATKBundle.subset.fa \
        BAIT_INTERVALS=interval_list/hg19_subset.interval_list \
        TARGET_INTERVALS=interval_list/hg19_subset.interval_list \
        PER_TARGET_COVERAGE=picard/reseq_no_refbias.hs_metrics.exon \
        PER_BASE_COVERAGE=picard/reseq_no_refbias.hs_metrics.base \
        MINIMUM_MAPPING_QUALITY=20 \
        MINIMUM_BASE_QUALITY=20
```

My expectation would be that most regions in the subsetted FASTA file have around 200X coverage (since I used the `--coverage 200` argument in the `reseq illuminaPE` command). However, when I run the following code in R:

```r

library("magrittr")
library("ggplot2")

in_df <- readr::read_tsv("picard/reseq_no_refbias.hs_metrics.exon")
in_df %>%
  dplyr::mutate(ind = dplyr::row_number()) %>%
  ggplot(aes(x = ind, y = mean_coverage)) +
  geom_point() +
  geom_hline(yintercept = 200, linetype = "dotted", color = "red")

ggsave("reseq_coverage.png")
```

This is the coverage:

![reseq_coverage](https://user-images.githubusercontent.com/3268173/107056744-91141800-67ca-11eb-84a4-f97165cb5fa6.png)

Where the horizontal dotted red line represents the expected coverage of 200X. 

There is definitely a lot of variance around the expected coverage of 200 and not what I would expect. Am I interpreting the `--refBias no` argument incorrectly? If so, how do I get as close to uniform coverage as possible?

The output files can be found [here](https://drive.google.com/drive/folders/1oPAitRV6REmTewB00ERNnuuBfoll1P4D?usp=sharing) under the folders:

* `sim_fastqs`: ReSeq simulated reads.
* `sim_bam`: BWA aligned BAM file of the ReSeq simulated reads.
* `picard`: Coverage statistics

**Comment by schmeing** [comment]
To have absolutely no biases you also need the `--noBias` option to remove the biases based on sequence content, which have a strong effect for your short sequences. With that option I get the following plot, where the sequences are sorted by length:

![coverage](https://user-images.githubusercontent.com/18011932/107854450-2e4efc00-6e1c-11eb-808b-6dfee35d555a.png)

The remaining issue is the sequence length itself. The fragments of various lengths need to be placed on the sequences. The simulator tries to do that respecting the fragment length distribution, which goes up to approximately 500 in your case. That means all positions up to 500 bases from the end have lower coverage and the closer they get the stronger is that effect.
How to fix this depends on what you want. For normal simulations the decrease at the ends is desired as this effect is also visible in real data, but if I understood it correctly that is not your intention. I could add a parameter to set a fixed fragment length, which you could set to the read length and you will reduce that effect as much as possible. An alternative would be to actively compensate the effect using the reference sequence bias. This would give you the best result in equal mean coverage of your sequences, but does not improve the uniformity within your sequence.

**Comment by tinyheero** [comment]
Hi @schmeing. 

Thanks for the reply. That was super helpful.

I didn't realize the `--noBias` argument was also required to get uniform coverage so thank you to pointing that out. Once, I used that argument I produced this coverage plot:

![reseq_with_nobias_argument](https://user-images.githubusercontent.com/3268173/107943927-49894b00-6f85-11eb-9c4e-763d1be2b35c.png)

This is much improved from before! I can also reproduce your coverage vs. sequence length plot. If I understand your above point:

> The remaining issue is the sequence length itself. The fragments of various lengths need to be placed on the sequences. The simulator tries to do that respecting the fragment length distribution, which goes up to approximately 500 in your case. That means all positions up to 500 bases from the end have lower coverage and the closer they get the stronger is that effect.

> How to fix this depends on what you want. For normal simulations the decrease at the ends is desired as this effect is also visible in real data, but if I understood it correctly that is not your intention. I could add a parameter to set a fixed fragment length, which you could set to the read length and you will reduce that effect as much as possible. An alternative would be to actively compensate the effect using the reference sequence bias. This would give you the best result in equal mean coverage of your sequences, but does not improve the uniformity within your sequence.

We should be expecting that the ends (and also the starts?) of the sequence to have lower coverage in real-world data. That makes sense because in order for you to get coverage near the ends (and starts?) of the sequence, you need a fragment that fits “within its bounds”. The most extreme example being that first and last position of the sequence where you would need the fragment to have a start and end at those respectively position to get any coverage. The following diagram might help articulate my thoughts better:

![coverage_example](https://user-images.githubusercontent.com/3268173/107944046-7b9aad00-6f85-11eb-87ce-3fe7f1817426.png)

This would explain why short sequences have lower coverage in general since less fragments by random chance would fit into the sequence. Have I got that correct?

Am I correct in understanding that when a fragment doesn’t fit into a reference sequence, another fragment gets sampled or does it get tossed? I am trying to understand why the average coverage is still not ~200X (despite using the `--coverage 200` argument). For instance, I constructed a simple null error sequence simulator that always samples within the reference sequence with a fixed fragment length (235) to try to understand the behaviour of simulators. This generate a coverage profile like this (this is not reflective of real world data obviously and only meant to simulate whether it's possible to get uniform coverage in the ideal scenario):

![uniform_coverage_incl_mm_reads](https://user-images.githubusercontent.com/3268173/107944377-eb109c80-6f85-11eb-82ed-e9342368cc04.png)

Is this simply because the fragment length has been fixed in my simplest simulator? 

To be clear, running ReSeq with uniform coverage is just a simple a positive control experiment before moving on to trying to simulate real-world coverage profiles. So the intention is to eventually use ReSeq's amazing features of mimicking real-world data. So I am just trying to understand it's expected behaviour at this point.

**Comment by schmeing** [comment]
ReSeq does not try to have an average 200x coverage on all sequences, but in total. Since it does not use a draw & reject, but a negative binomial for better simulation of duplicates it is a bit more complicated than redrawing rejected reads. However, it estimates the coverage taking everything into account, except variants. Thus, you are correct that the longer sequences should have > 200x coverage. This is the behaviour we see in my plot. I expect your reduced coverage being a consequence of your parameters for the depth extraction:
```
MINIMUM_MAPPING_QUALITY=20 \
MINIMUM_BASE_QUALITY=20
```

**Comment by tinyheero** [comment]
Thanks for clarifying how the ReSeq simulation works. 

In terms of coverage being lower than expected, you are right that it's a byproduct of how the coverage is being calculated. I took another look at the Picard output on the summary coverage:

```
> awk 'NR==7 || NR==8' reseq_no_refbias.hs_metrics.txt \
    | csvcut -t -c "MEAN_BAIT_COVERAGE,MEAN_TARGET_COVERAGE,PCT_EXC_OVERLAP" \
    | csvlook -I

| MEAN_BAIT_COVERAGE | MEAN_TARGET_COVERAGE | PCT_EXC_OVERLAP |
| ------------------ | -------------------- | --------------- |
| 197.844378         | 153.221107           | 0.403918        |
```

According to this issue (https://github.com/broadinstitute/picard/issues/476), the `MEAN_BAIT_COVERAGE` reflects the raw coverage (i.e. before any filters) while `MEAN_TARGET_COVERAGE` reflects coverage that has been filtered. In particular, what appears to be the driving factor in the `PCT_EXC_OVERLAP`, which appears to reflect the proportion of aligned bases being filtered out from the Picard coverage due to overlapping paired-ends (Note: I ran the Picard command with a 0 threshold for the mapping and base quality threholds and it made no difference).

As such, these data support your point about how the reported coverage is lower only because how it is being reported.  Importantly, ReSeq appears to be achieving 200X coverage at the raw simulated read level.

Thanks for the replies and clarifying things. Much appreciated!
