### ISSUE TITLE
Reseq failed

### ISSUE THREAD

**Issue by lmanchon** [schmeing/ReSeq#16]
--Hi,

it failed with:
reseq illuminaPE -j 16 -r chr20.fa -b my_mappings.bam -1 chr20_1.fastq -2 chr20_2.fastq
!!! bool reseq::AdapterStats::PredictAdapters() [/opt/conda/conda-bld/reseq_1616891573911/work/reseq/AdapterStats.cpp:601]: error: Only non-extendible sequences were found as adapter for read 2

i have first generated chr20_1.fastq and chr20_2.fastq from chr20.fa with art_illumina tool in paired-end mode, then mapped them with bowtie2 as suggested:
bowtie2-build chr20.fa my_reference
bowtie2 -p 16 -X 2000 -x my_reference -1 chr20_1.fastq -2 chr20_2.fastq | samtools sort -m 20G -@ 4 -T _tmp -o my_mappings.bam 

seems to be an adapter problem, how to avoid this error ?

thank you --
-

**Comment by schmeing** [comment]
This was discussed in length in #2. If this does not answer your question, please reopen and explain in more detail.
