### ISSUE TITLE
Hanging after "Preparing for simulation" output

### ISSUE THREAD

**Issue by steven-solar** [schmeing/ReSeq#17]
I ran: 
```reseq illuminaPE -j 32 -r my_reference.fa -b my_mappings.bam --statsOnly```
```reseq illuminaPE -j 32 -s my_mappings.bam.reseq --stopAfterEstimation```
```reseq illuminaPE -j 32 -R my_reference.fa -s my_mappings.bam.reseq --ipfIterations 0 -1 my_simulated_data_1.fq -2 my_simulated_data_2.fq```
And on the final step, the program hangs after printing "Preparing for simulation" and never gives any further output and I have to force terminate it. Any idea what may be causing this?

**Comment by schmeing** [comment]
I have no clue. If you provide me with the files my_reference.fa and my_mappings.bam.reseq I can have a look what is going on. Either provide the links here or currently stephan.schmeing@uzh.ch is still active and you can send them there.

**Comment by steven-solar** [comment]
Sorry, but I think it was an issue with a virtual environment not having the memory capacity necessary to run the simulation, and have resolved it. Thank you!
