### ISSUE TITLE
Not able to run ReSeq !!! bool reseq::DataStats::ReadBam 

### ISSUE THREAD

**Issue by nicola-debernardini** [schmeing/ReSeq#18]
Hi,

I am trying to use ReSeq with the following genome GCF_000005845.2_ASM584v2 and reads SRR490124 downloaded from NCBI but I go an error apparently associated with the bam file. 

To generate the bam I used the same command suggested in the Quick start examples:  
bowtie2-build GCF_000005845.2_ASM584v2.fa GCF_000005845.2_ASM584v2_DB
bowtie2 -p 32 -X 2000 -x GCF_000005845.2_ASM584v2_DB -1 ./SRR490124_pass_1.fastq.gz  -2 ./SRR490124_pass_2.fastq.gz | samtools sort -@ 4 -o SRR490124.bam -

The sorted bam I got looks good to me:
![immagine](https://user-images.githubusercontent.com/45240213/181252193-bf1a9440-84ca-46fd-a47e-799a3790c0e4.png)

And to run ReSeq I used the following command and I got this error:
./bin/reseq illuminaPE -j 32 -r ./GCF_000005845.2_ASM584v2_genomic.fasta -b ./SRR490124.bam -1 ./SRR490124_pass_1.fastq.gz -2 ./SRR490124_pass_2.fastq.gz 

>>> 27-07-22 12:59:04: info:  Running ReSeq version 1.1 in illuminaPE mode
>>> 27-07-22 12:59:04: info:  Reading reference from /home/bioinfo/users/niber/phd/coli/MG1655/NC_000913.3/genome/GCF_000005845.2_ASM584v2_genomic.fasta
>>> 27-07-22 12:59:04: info:  Read in 1 reference sequences.
>>> 27-07-22 12:59:04: info:  Reading mapping from /home/bioinfo/users/niber/phd/coli/MG1655/reads_MG1655/reseq/SRR490124.bam
>>> 27-07-22 12:59:04: info:  Storing real data statistics in /home/bioinfo/users/niber/phd/coli/MG1655/reads_MG1655/reseq/SRR490124.bam.reseq
>>> 27-07-22 12:59:04: info:  Tiles will be ignored and all statistics will be generated like all reads are from the same tile.
>>> 27-07-22 12:59:04: info:  Starting PreRun
>>> 27-07-22 12:59:30: info:  Finished PreRun
Total number of reads: 21553358
Read length: 100 - 100
Read length on reference: 82 - 110
Quality: 2 - 40 ( 33-based encoding )
Mapping Quality: 0 - 42
Maximum InDel Length: 18
>>> 27-07-22 12:59:30: info:  Detected adapter 2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
>>> 27-07-22 12:59:30: info:  Detected adapter 1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG
>>> 27-07-22 12:59:30: info:  Starting main read-in
>>> 27-07-22 12:59:31: info:  Read 5% of the reads.
>>> 27-07-22 12:59:33: info:  Read 10% of the reads.
>>> 27-07-22 12:59:35: info:  Read 15% of the reads.
>>> 27-07-22 12:59:37: info:  Read 20% of the reads.
>>> 27-07-22 12:59:38: info:  Read 25% of the reads.
>>> 27-07-22 12:59:41: info:  Read 30% of the reads.
>>> 27-07-22 12:59:43: info:  Read 35% of the reads.
>>> 27-07-22 12:59:44: info:  Read 40% of the reads.
>>> 27-07-22 12:59:46: info:  Read 45% of the reads.
>>> 27-07-22 12:59:48: info:  Read 50% of the reads.
>>> 27-07-22 12:59:49: info:  Read 55% of the reads.
>>> 27-07-22 12:59:53: info:  Read 60% of the reads.
>>> 27-07-22 12:59:54: info:  Read 65% of the reads.
>>> 27-07-22 12:59:56: info:  Read 70% of the reads.
>>> 27-07-22 12:59:58: info:  Read 75% of the reads.
>>> 27-07-22 12:59:59: info:  Read 80% of the reads.
>>> 27-07-22 13:00:01: info:  Read 85% of the reads.
>>> 27-07-22 13:00:03: info:  Read 90% of the reads.
>>> 27-07-22 13:00:04: info:  Read 95% of the reads.
>>> 27-07-22 13:00:06: info:  Read 100% of the reads.
>>> 27-07-22 13:00:15: info:  Needed to create 465 coverage blocks.
>>> 27-07-22 13:00:15: info:  Excluded 100 of 4641652 bases [0%] in the reference due to contig ends and N's over 2 regions.
>>> 27-07-22 13:00:15: info:  Finished processing all reads.
>>> 27-07-22 13:00:15: info:  Of the 21553358 reads in the file
>>> 27-07-22 13:00:15: info:  0 (0%) could be used for all statistics
>>> 27-07-22 13:00:15: info:  0 (0%) had too low mapping qualities with adapters detected
>>> 27-07-22 13:00:15: info:  0 (0%) had too low mapping qualities without adapters detected
>>> 27-07-22 13:00:15: info:  0 (0%) mapped to excluded regions of the reference
>>> 27-07-22 13:00:15: info:  21553358 (100%) were mapping too far apart from their partner or in wrong direction
>>> 27-07-22 13:00:15: info:  0 (0%) are on reference sequences that are too short
>>> 27-07-22 13:00:15: info:  0 (0%) were in an unmapped pair with adapters detected
>>> 27-07-22 13:00:15: info:  0 (0%) were in an unmapped pair without adapters detected
!!! bool reseq::DataStats::ReadBam(const char*, const char*, const char*, const string&, reseq::uintSeqLen, reseq::uintNumThreads, bool) [/home/bioinfo/bin/ReSeq/reseq/DataStats.cpp:1257]: error: No reads in the file passed all criteria to be used for the statistics

Could you help me understand how does the program is expecting me to align the reads since in theory the reads I selected are also part of one of the test case? 

Thank you!

**Comment by schmeing** [comment]
Hi,

Thank you for reporting this. The filter that filters all your reads:
`27-07-22 13:00:15: info: 21553358 (100%) were mapping too far apart from their partner or in wrong direction`
Checks if the reads map in the forward-reverse order typical for Illumina paired-end and if they are not further than 2000 apart. Could you look at a few pairs and let me know, what the distances and orientation are, please?

**Comment by jo-mc** [comment]
You have a different file name for the reference used in bowtie and the one used in reseq, check they are the same. ?

I've been meaning to look at this so tried 'reseq' out on the data set you used.

I seemed to run it ok and generated output reads. see attached notes and output. (though my bam did not have .1 and .2 appended to qname)

[run_output_and_notes.txt](https://github.com/schmeing/ReSeq/files/9205293/run_output_and_notes.txt)

**Comment by nicola-debernardini** [comment]
Hi,

Thanks for giving it a look!
At the end was a problem of the reads I downloaded because their name included an extra number to specify the mate pare (e.g. SRR490124.5521767.**1** and SRR490124.5521767.**2**).

Once I removed the extra number in the name of the reads in the sam file ReSeq worked perfectly.

Original bam: >>> samtools view SRR490124-srt.bam | head
![immagine](https://user-images.githubusercontent.com/45240213/182930907-5bb77f82-ff49-4692-b6f7-b603b12da766.png)

Corrected bam: >>> samtools view SRR490124-cor-srt.bam | head
![immagine](https://user-images.githubusercontent.com/45240213/182930828-5d758849-e3f7-4fba-aeae-657360671bca.png)

**Comment by schmeing** [comment]
Sorry, that I missed this. The newest version on git also gives warnings when it does not find the other read of a pair.
To fix these files I have python script that also adds the tile information (although by default it is not used, because it does not really improve the result if you are not interested in tile effects and makes it much slower for some datasets):
```
bowtie2 -p 32 -X 2000 -x my_reference -1 <(reseq-prepare-names.py my_data_1.fq my_data_2.fq) -2 <(reseq-prepare-names.py my_data_2.fq my_data_1.fq) | samtools sort -m 10G -@ 4 -T _tmp -o my_mappings.bam -
```
