### ISSUE TITLE
Questions on ReSeq

### ISSUE THREAD

**Issue by JappyPing** [schmeing/ReSeq#19]
Hi,
Thanks for the excellent tool to simulate NGS data. 

- When I was generating the "my_mappings.bam" using bowtie2 with the following commands,

`bowtie2-build my_reference.fa my_reference
bowtie2 -p 32 -X 2000 -x my_reference -1 my_data_1.fq -2 my_data_2.fq | samtools sort -m 10G -@ 4 -T _tmp -o my_mappings.bam -`

I got the following errors,
`Saw ASCII character 10 but expected 33-based Phred qual.
terminate called after throwing an instance of 'int'
(ERR): bowtie2-align died with signal 6 (ABRT)`
This error seems like a known bug of bowtie2 [(https://github.com/BenLangmead/bowtie2/issues/218)]. Could you please give me some suggestions?

- Alternatively, I am considering applying errors and qualities directly to sequences using the following provided commands
`reseq seqToIllumina -j2 -i my_sequences.fa -o my_simulated_reads.fq -s my_stats_profile.reseq`
so, in the above example, is the fie file my_sequences.fa the ground truth file compared with the simulated data my_simulated_reads.fq? 

and is there any function that can generate the required my_refeence.fa directly? By calling the commands `reseq illuminaPE -r my_reference.fa -s my_stats_profile.reseq --stopAfterEstimation --writeSysError my_systematic_errors.fq`, reseq can produce my_systematic_errors.fq, but I am confused about how to integrate the my_systematic_errors.fq into my_sequences.fa or use it `with` the commands `reseq seqToIllumina.` I really appreciate it if you could give me more detailed instructions.

Best regards,

Jappy

**Comment by schmeing** [comment]
For bowtie2 I would recommend to look into the following parameter:
```
  --int-quals        qualities encoded as space-delimited integers
```
What is your encoding if it is not phred33 or phred64? This does not sound like Illumina data?

Alternatively, you can also align with bwa in case it helps.

```
reseq seqToIllumina -j2 -i my_sequences.fa -o my_simulated_reads.fq -s my_stats_profile.reseq
```
You can use to simulate data without a reference, but you still need a profile, which needs a bam file and a reference in fasta.

**Comment by JappyPing** [comment]
> For bowtie2 I would recommend to look into the following parameter:
> 
> ```
>   --int-quals     qualities encoded as space-delimited integers
> ```
> 
> What is your encoding if it is not phred33 or phred64? This does not sound like Illumina data?
> Alternatively, you can also align with bwa in case it helps.

1. It was really wired, there should be some unproper settings during my test because I was using the real datasets (e.g. SRR490124) used in your paper for alignment. I will try to use the above recommendations. Thanks so much for your help.


> 
> ```
> reseq seqToIllumina -j2 -i my_sequences.fa -o my_simulated_reads.fq -s my_stats_profile.reseq
> ```
> 
> You can use to simulate data without a reference, but you still need a profile, which needs a bam file and a reference in fasta.

2. This alternative function seems great, but it is a little confusing. 

- " You can use to simulate data `without a reference`," do you mean this reference is a genome reference? 

- "but you still need a profile, which `needs` a bam file and `a reference` in fasta." What does this reference mean? 

- "but you still need a profile, which `needs a bam file` and a reference in fasta."
The required bam file has to be generated from aligning real sequencing data to the genome reference, in this case, alignment is a mandatory step. Am I understanding right? Thanks so much for your time and efforts in explaining.

**Comment by schmeing** [comment]
1. SRR490124 does not have ASCII character 10 as quality score. So you are right, something else is wrong. Was there an issue during the download that the file is not complete or has some errors? You can verify with an `md5sum`, they are normally stated for the downloaded files.
Or is the file compressed? That sometimes causes problems and interpreting binary data as ascii leads to all sorts of normally not expected characters.
2. The simulation has two steps. First, the reads are randomly selected from the provided reference following some previously learned distributions. Second, quality scores and errors are added to the reads based on previously learned distributions. Using the seqToIllumina command you skip part one and only use part two. Thus, you do not provide a reference, but directly the reads. This you can use when the selection from the reference does not fit your use case or you want to change something before. I consider this advanced use and so far the users have been other developers.
Independently, on how you generated the reads for adding qualities and errors you need to learn the distributions beforehand (the profile) and for this you need the alignment, so yes it is a mandatory step. The only alternative is to use a previously created profile, like for example one from here:
https://github.com/schmeing/ReSeq-profiles
