### ISSUE TITLE
Are there plans for a Bioconda release?

### ISSUE THREAD

**Issue by rpetit3** [schmeing/ReSeq#4]

**Comment by schmeing** [comment]
Yes, it is definitely planned, but I haven't found the time yet to learn how to create a conda package.

**Comment by schmeing** [comment]
Sorry that it took so long. The devel branch has now a folder conda with the receipt. It seems to work, but if you are experienced with creating conda packages you could check if I need to fix or improve it.
I am currently testing the devel on multiple datasets to check if I accidentally added a new bug and probably around end of the month I plan to merge devel into master as version 1.1. This version I also plan to upload to bioconda.

**Comment by schmeing** [comment]
Again much later then expected, but it is available through bioconda by now.

**Comment by rpetit3** [comment]
That's awesome! Great stuff!
