### ISSUE TITLE
Null Sequencing Error 

### ISSUE THREAD

**Issue by cilliannolan** [schmeing/ReSeq#6]
Hello,

I am hoping to use Reseq to create a dataset without introduced sequencing error. 
Would this be possible in Reseq? I was unable to find an option in the documentation for this.

Kind regards,
Cillian

**Comment by schmeing** [comment]
Currently, there is only a parameter for substitution errors, but additional parameters can be quickly added. I assume you want neither substitution nor InDel errors. And to clarify, you do not want an additional error free version of the simulated reads, but only the error free reads distributed according to the negative binomial coverage model and having proper quality values (which then do not relate to the error rates).

**Comment by cilliannolan** [comment]
So to expand on what we are trying to achieve:

We currently make use of Wessim for read simulating, however we discovered Wessim introduces many sequencing errors (even when the sequencing error model is a Null model) which is problematic for downstream SNP calling as there are many false positives.

We are hoping to find a tool which will simulate reads directly from a FASTA file, at least when no sequencing error is introduced.

If I understand correctly what I want would be an option for no substitution and no InDel errors.

**Comment by schmeing** [comment]
I added the parameters `--noInDelErrors` and `--noSubstitutionErrors` to the devel branch. Try it out and let me know if this is what you need. Just be aware that adapters are still present in the simulated data and lead to errors when mapping. The reads do have a CIGAR string in the read id (after a space, so they are not in the mapping files, so that paired reads have identical names there). The S encodes adapters and can be used to trim those off if you want to.

**Comment by cilliannolan** [comment]
I will keep the adapters in mind. Thank you very much and I will let you know how it goes.

**Comment by cilliannolan** [comment]
Hi again, just trying out the devel branch now and getting the error message:
"error: Could not parse illuminaPE command line arguments: unrecognised option '--noIndelErrors'"

**Comment by schmeing** [comment]
It is case sensitive and supposed to be `--noInDelErrors`. If this is wrongly documented somewhere, please let me know.

**Comment by cilliannolan** [comment]
You are correct, and no that is my mistake!
