### ISSUE TITLE
(Incorrect?) input configuration causing SegFault

### ISSUE THREAD

**Issue by mlinderm** [schmeing/ReSeq#8]
https://github.com/schmeing/ReSeq/blob/3279e764f74809460e4c702fa9434dabf277e83a/reseq/Simulator.cpp#L656

I just discovered your preprint and I am really excited to try out this simulator. After some initial successful test runs, I am now running into an intermittent SegFault at the above line. Specifically, `end_block` is a null pointer, e.g.

```
Thread 4 "reseq" received signal SIGSEGV, Segmentation fault.
reseq::Simulator::CreateReads (this=this@entry=0x7ffffffc7b00, ref=..., stats=..., estimates=..., rdist=..., sim_reads=..., rgen=..., counts=1, 
    strand=true, allele=1, ref_seq_id=0, fragment_length=997, read_number=@0x2aaab03bf6b8: 80, start_block=0x5555578f57f0, start_position_forward=2714, 
    end_position_forward=6071, start_variant=..., end_variant=...) at /usr/local/src/conda/reseq-1.1/reseq/Simulator.cpp:656
656     in /usr/local/src/conda/reseq-1.1/reseq/Simulator.cpp
(gdb) p end_block
$5 = (const reseq::Simulator::SimBlock *) 0x0
```

I am trying to simulate SVs in isolation, so I am providing a small snippet of the reference genome, e.g., the SV with a 3kb flank, and a VCF with the variant shifted into that new coordinate space as the input to ReSeq. I attached the inputs that cause the SegFault: [ReSeqTestInputs.zip](https://github.com/schmeing/ReSeq/files/5788587/ReSeqTestInputs.zip). The command line is:

```
reseq illuminaPE -j 1 --refSim test.fasta -s test.reseq -V test.vcf -c 25.4 --ipfIterations 0 -1 reads.synth11.fq -2 reads.synth12.fq
```

Is this incorrect usage? If so, is there a correct/better way to simulate variants in just a small portion of the genome? Thanks!

**Comment by schmeing** [comment]
Thanks a lot for finding this bug. For short deletions it only rarely leads to a crash and is therefore super hard to track down. I pushed the fix to the devel branch.

**Comment by mlinderm** [comment]
Awesome! Thanks for the quick response! I will give that a try.
